before_install:
 - pip install --upgrade pip wheel
language: python
cache: apt
sudo: false
python:
 - '2.7'
install:
 - pip install requests
script:
 - python fetch-v2.py
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
